In [1]:
import numpy as np

In [ ]:
# Create an array

a = np.array([1,2,3,4,5])

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
# check the dimension

In [ ]:
a.ndim

1

In [ ]:
# Create a two dimensional array

b = np.array([[1,2,3],[4,5,6]])

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b.ndim

2

In [ ]:
# Create a three dimensional array
ar=np.array([[[1,2,3],[4,5,6]]])

In [ ]:
ar

array([[[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
ar.ndim

3

In [ ]:
## Zero's and One's

var = np.zeros(10)

In [ ]:
var

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
var1 = np.ones(10)

In [ ]:
var1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# create an array with all one's, 3 internal arrays with 4 rows and 5 columns

np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [ ]:
# create an array with 4 internal arrays 2 rows 3 columns all the elements should be zero
np.zeros((4,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
## Functions

In [ ]:
Var = np.array([22,35,17,27,45])
Var

array([22, 35, 17, 27, 45])

In [ ]:
type(Var)

numpy.ndarray

In [ ]:
Var.argmax()   # ma value in index position

4

In [ ]:
Var.argmin()  # min index value

2

In [ ]:
Var[0]

22

In [ ]:
Var[1:3]

array([35, 17])

In [ ]:
Var[:-1]

array([22, 35, 17, 27])

In [ ]:
Var1 = np.array([22,35,17,27,45,23.1,1.9])


In [ ]:
Var1

array([22. , 35. , 17. , 27. , 45. , 23.1,  1.9])

In [ ]:
Var1.dtype

dtype('float64')

In [ ]:
Var1.size

7

In [ ]:
# Create a numpy array with size 5 datatype of float

arr = np.array([1,2,3,4,5.0])

arr.size

5

In [ ]:
arr.dtype

dtype('float64')

In [ ]:
arr

array([1., 2., 3., 4., 5.])

In [ ]:
# Create a two dim array
# four arrays in the external array
# it should have  two elements each

In [2]:
v = np.array([[1,2],[3,4],[1,5],[5,7]])

In [3]:
v

array([[1, 2],
       [3, 4],
       [1, 5],
       [5, 7]])

In [4]:
v.ndim

2

In [ ]:
## Resize & Reshape

In [6]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
a.ndim

1

In [10]:
r =np.arange(12).reshape(4,3)
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
r.max()

11

In [12]:
r.min()

0

In [13]:
np.sqrt(r)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])

In [14]:
np.log(r)

<ipython-input-14-487c15201b95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(r)


array([[      -inf, 0.        , 0.69314718],
       [1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527]])

In [15]:
np.exp(r)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [16]:
## Transpose

r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
t = r.T
t

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [24]:
## floor & Ceil


arr2 = np.array([1.3,3.48,6.12,5.9,9.1])
arr2

array([1.3 , 3.48, 6.12, 5.9 , 9.1 ])

In [25]:
np.floor(arr2)

array([1., 3., 6., 5., 9.])

In [26]:
np.ceil(arr2)

array([ 2.,  4.,  7.,  6., 10.])

In [27]:
np.round(arr2)

array([1., 3., 6., 6., 9.])

In [ ]:
## stacking

In [28]:
arr23 = np.arange(10).reshape(2,5)
arr23

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
arr24 =np.arange(20).reshape(4,5)
arr24

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [30]:
np.vstack((arr23,arr24))    # vertical stacking

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [31]:
np.hstack((arr23,arr24))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 4

In [ ]:
## for vstack the number of columns should be same and for hstack the number of rows should be same for two arrays

In [32]:
arr13 = np.arange(15).reshape(3,5)
arr13

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
arr14 = np.arange(12).reshape(3,4)
arr14

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
np.hstack((arr13,arr14))

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3],
       [ 5,  6,  7,  8,  9,  4,  5,  6,  7],
       [10, 11, 12, 13, 14,  8,  9, 10, 11]])

In [35]:
np.vstack((arr13,arr14))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 4

In [ ]:
## Numpy Split

In [36]:
arr15 = np.arange(100).reshape(10,10)
arr15

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [37]:
np.vsplit(arr15,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])]

In [38]:
np.hsplit(arr15,2)

[array([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34],
        [40, 41, 42, 43, 44],
        [50, 51, 52, 53, 54],
        [60, 61, 62, 63, 64],
        [70, 71, 72, 73, 74],
        [80, 81, 82, 83, 84],
        [90, 91, 92, 93, 94]]),
 array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19],
        [25, 26, 27, 28, 29],
        [35, 36, 37, 38, 39],
        [45, 46, 47, 48, 49],
        [55, 56, 57, 58, 59],
        [65, 66, 67, 68, 69],
        [75, 76, 77, 78, 79],
        [85, 86, 87, 88, 89],
        [95, 96, 97, 98, 99]])]

In [ ]:
# create a numpy array with shape of 200, array should be contains 20 rows and 10 columns,
# split the array in to vertically and horizondally.

In [40]:
A=np.arange(200).reshape(20,10)
np.vsplit(A,2)


[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]),
 array([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165, 166, 167, 168, 169],
        [170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
        [180, 181,

In [41]:
np.hsplit(A,2)

[array([[  0,   1,   2,   3,   4],
        [ 10,  11,  12,  13,  14],
        [ 20,  21,  22,  23,  24],
        [ 30,  31,  32,  33,  34],
        [ 40,  41,  42,  43,  44],
        [ 50,  51,  52,  53,  54],
        [ 60,  61,  62,  63,  64],
        [ 70,  71,  72,  73,  74],
        [ 80,  81,  82,  83,  84],
        [ 90,  91,  92,  93,  94],
        [100, 101, 102, 103, 104],
        [110, 111, 112, 113, 114],
        [120, 121, 122, 123, 124],
        [130, 131, 132, 133, 134],
        [140, 141, 142, 143, 144],
        [150, 151, 152, 153, 154],
        [160, 161, 162, 163, 164],
        [170, 171, 172, 173, 174],
        [180, 181, 182, 183, 184],
        [190, 191, 192, 193, 194]]),
 array([[  5,   6,   7,   8,   9],
        [ 15,  16,  17,  18,  19],
        [ 25,  26,  27,  28,  29],
        [ 35,  36,  37,  38,  39],
        [ 45,  46,  47,  48,  49],
        [ 55,  56,  57,  58,  59],
        [ 65,  66,  67,  68,  69],
        [ 75,  76,  77,  78,  79],
        [ 85,  86,