## Tensor(Constant)

In [1]:
# tf.Tensor - 2 attributes:-> Tensor.shape,Tensor.dtype

In [2]:
import tensorflow as tf

In [3]:
## Scalar or rank-0 tensor
# A scalar contrains a single value and no axes

rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
## vector or rank_1_ tensor
# Is a line of values, A vector has one axis

rank_1_tensor = tf.constant([4,3,5,6])
print(rank_1_tensor)

tf.Tensor([4 3 5 6], shape=(4,), dtype=int32)


In [5]:
## A "matrix" or rank_2_tensor
# It has two axes

rank_2_tensor = tf.constant([[1,2],[3,4,],[5,6]])
print(rank_2_tensor)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [6]:
rank_3_tensor = tf.constant([[[1,2],[3,4]]])
print(rank_3_tensor)

tf.Tensor(
[[[1 2]
  [3 4]]], shape=(1, 2, 2), dtype=int32)


In [7]:
rank_3 =tf.constant([[[1,3],[2,3],[3,4],[6,8]]])
print(rank_3)

tf.Tensor(
[[[1 3]
  [2 3]
  [3 4]
  [6 8]]], shape=(1, 4, 2), dtype=int32)


In [8]:
# convert a tensor to numpy array

import numpy as np
np.array(rank_3)


array([[[1, 3],
        [2, 3],
        [3, 4],
        [6, 8]]], dtype=int32)

In [9]:
tensor_1 = tf.constant([[1,2.3,3],[4,5,6]])
print(tensor_1)
print(tensor_1.shape)
print(tensor_1.dtype)


tf.Tensor(
[[1.  2.3 3. ]
 [4.  5.  6. ]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


In [10]:
# Addition
tensor_1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1. , 2.3, 3. ],
       [4. , 5. , 6. ]], dtype=float32)>

In [11]:
tensor_2 = tf.constant([[4,6,8],[4.2,2,6.1]])
tensor_2

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[4. , 6. , 8. ],
       [4.2, 2. , 6.1]], dtype=float32)>

In [12]:
tensor_1+tensor_2

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 5. ,  8.3, 11. ],
       [ 8.2,  7. , 12.1]], dtype=float32)>

In [13]:
5 * tensor_1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 5. , 11.5, 15. ],
       [20. , 25. , 30. ]], dtype=float32)>

In [14]:
tf.transpose(tensor_1)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1. , 4. ],
       [2.3, 5. ],
       [3. , 6. ]], dtype=float32)>

In [15]:
tensor_1 @ tf.transpose(tensor_1) # matrix multiplication

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[15.29, 33.5 ],
       [33.5 , 77.  ]], dtype=float32)>

In [16]:
tf.matmul(tensor_1, tf.transpose(tensor_1)) # matrix multiplication

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[15.29, 33.5 ],
       [33.5 , 77.  ]], dtype=float32)>

In [17]:
tensor_1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1. , 2.3, 3. ],
       [4. , 5. , 6. ]], dtype=float32)>

In [18]:
tensor_4 = 5 * tensor_1
tensor_4

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 5. , 11.5, 15. ],
       [20. , 25. , 30. ]], dtype=float32)>

In [21]:
tf.concat([tensor_1,tensor_4],axis =0)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 1. ,  2.3,  3. ],
       [ 4. ,  5. ,  6. ],
       [ 5. , 11.5, 15. ],
       [20. , 25. , 30. ]], dtype=float32)>

In [ ]:
# tf.nn
# TensorFlow 2.x - tf.keras.layers

In [22]:
tf.reduce_sum(tensor_1)   # sum of all elements in a tensor

<tf.Tensor: shape=(), dtype=float32, numpy=21.3>

In [23]:
li = tf.convert_to_tensor ([3,5,6,7]) # list to tensor
li

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 5, 6, 7], dtype=int32)>

## Variables

In [31]:
var_1 = tf.Variable([4,3.4,6])

In [32]:
var_1

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([4. , 3.4, 6. ], dtype=float32)>

In [33]:
var_1.assign_add([1,5,1])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=float32, numpy=array([5. , 8.4, 7. ], dtype=float32)>

In [34]:
var_1.assign([3,2,1])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=float32, numpy=array([3., 2., 1.], dtype=float32)>

In [35]:
bool_variable =tf.Variable([False,True,False])
bool_variable

<tf.Variable 'Variable:0' shape=(3,) dtype=bool, numpy=array([False,  True, False])>

In [36]:
complex_variable = tf.Variable([5+2j,1+3j])
complex_variable

<tf.Variable 'Variable:0' shape=(2,) dtype=complex128, numpy=array([5.+2.j, 1.+3.j])>